# Generated by Django 6.0.2 on 2026-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('passout_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
