# Generated by Django 6.0.2 on 2026-03-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_id', models.CharField(max_length=10)),
                ('prof_name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
