# Generated by Django 6.0.3 on 2026-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='degree',
            field=models.CharField(default='Btech', max_length=100),
            preserve_default=False,
        ),
    ]
